export const userMockupDodyy = {
  user_id: "dodyy14",
  nickname: "Mì ❄️",
  profile_url:
    "https://i.pinimg.com/736x/79/af/a7/79afa717d253fd6be40d8796ba5028d2.jpg",
  require_auth_for_profile_image: false,
};

export const userMockupB = {
  user_id: "christ",
  nickname: "Phan Ngọc Loan 🌿",
  profile_url:
    "https://i.pinimg.com/564x/f1/32/15/f13215c0852658c796806ab0f7e16b02.jpg",
  require_auth_for_profile_image: false,
};

export const userMockupC = {
  user_id: "dania",
  nickname: "Dania 💧",
  profile_url:
    "https://i.pinimg.com/736x/ef/71/d0/ef71d0b7da66741b8b87691df12f9eaa.jpg",
  require_auth_for_profile_image: false,
};

export const userMockupF = {
  user_id: "eauzan",
  nickname: "🥝 Eauzan",
  profile_url:
    "https://i.pinimg.com/564x/d8/a7/9d/d8a79df59c79c90f666b5054b9ba3c14.jpg",
  require_auth_for_profile_image: false,
};

export const userMockupE = {
  user_id: "fazaaa",
  nickname: "『CT』┊ ㊝Fazaa亗 ",
  profile_url:
    "https://i.pinimg.com/564x/ec/37/16/ec37168707d06fe32c106faaecc5706e.jpg",
  require_auth_for_profile_image: false,
};

export const channelsMockup = [
  {
    channel_url:
      "sendbird_group_channel_418411068_2326cc40d54ee27f89a28ebf144503b2b7597f34",
    name: "Group Channel",
    cover_url: "https://static.sendbird.com/sample/cover/cover_11.jpg",
    data: "",
    member_count: 2,
    joined_member_count: 2,
    max_length_message: 5000,
    created_at: 1712158333,
    custom_type: "CHANNEL_USER",
    is_distinct: false,
    is_super: false,
    is_broadcast: false,
    is_public: true,
    is_discoverable: true,
    freeze: false,
    is_ephemeral: false,
    unread_message_count: 2,
    unread_mention_count: 0,
    ignore_profanity_filter: false,
    id: 1106969225,
    channel: {
      channel_url:
        "sendbird_group_channel_418411068_2326cc40d54ee27f89a28ebf144503b2b7597f34",
      name: "Group Channel",
      cover_url: "https://static.sendbird.com/sample/cover/cover_11.jpg",
      data: "",
      created_at: 1712158333,
      custom_type: "CHANNEL_USER",
      max_length_message: 5000,
      member_count: 2,
    },
    count_preference: "all",
    created_by: userMockupDodyy,
    disappearing_message: {
      is_triggered_by_message_read: false,
      message_survival_seconds: -1,
    },
    is_access_code_required: true,
    is_muted: false,
    is_push_enabled: true,
    member_state: "joined",
    message_survival_seconds: -1,
    my_role: "",
    push_trigger_option: "default",
    read_receipt: {
      [userMockupDodyy.user_id]: 1713337561127,
      [userMockupB.user_id]: 1712893833869,
    },
    sms_fallback: {
      wait_seconds: -1,
      exclude_user_ids: [],
    },
    ts_message_offset: 0,
    user_last_read: 1713337561127,
    inviter: {
      ...userMockupB,
      metadata: {},
    },
    invited_at: 1713337561127,
    is_hidden: false,
    hidden_state: "unhidden",
    last_message: {
      type: "MESG",
      message_id: 2178333742,
      message: "Hi Mì ❄️!\nGlad to know you!",
      data: "",
      custom_type: "",
      file: {},
      created_at: 1713345635492,
      user: userMockupB,
      channel_url:
        "sendbird_group_channel_418411068_2326cc40d54ee27f89a28ebf144503b2b7597f34",
      updated_at: 0,
      message_survival_seconds: -1,
      mentioned_users: [],
      mention_type: "users",
      silent: false,
      message_retention_hour: -1,
      channel_type: "group",
      translations: {},
      is_removed: false,
      req_id: "rq-ba033f4f-3faf-414b-b50b-5e811f69bb58",
      is_op_msg: false,
      message_events: {
        send_push_notification: "receivers",
        update_unread_count: true,
        update_mention_count: true,
        update_last_message: true,
      },
    },
    members: [
      {
        ...userMockupDodyy,
        metadata: {},
        is_online: true,
        last_seen_at: 0,
        state: "joined",
        is_active: true,
        is_blocked_by_me: false,
        friend_name: null,
        friend_discovery_key: null,
        role: "",
        is_muted: false,
        muted_end_at: -1,
        muted_description: "",
        is_blocking_me: false,
      },
      {
        ...userMockupB,
        metadata: {},
        is_online: false,
        last_seen_at: -1,
        state: "joined",
        is_active: true,
        is_blocked_by_me: false,
        friend_name: null,
        friend_discovery_key: null,
        role: "",
        is_muted: false,
        muted_end_at: -1,
        muted_description: "",
        is_blocking_me: false,
      },
    ],
    operators: [],
    joined_ts: 1713337561,
  },
  {
    channel_url:
      "sendbird_group_channel_418411068_2326cc40d54ee27f89a28ebf144503b2b7597a34",
    name: "Group Channel",
    cover_url: "https://static.sendbird.com/sample/cover/cover_11.jpg",
    data: "",
    member_count: 0,
    joined_member_count: 0,
    max_length_message: 5000,
    created_at: 1712158333,
    custom_type: "CHANNEL_USER",
    is_distinct: false,
    is_super: false,
    is_broadcast: false,
    is_public: true,
    is_discoverable: true,
    freeze: false,
    is_ephemeral: false,
    unread_message_count: 2,
    unread_mention_count: 0,
    ignore_profanity_filter: false,
    id: 1106969225,
    channel: {
      channel_url:
        "sendbird_group_channel_418411068_2326cc40d54ee27f89a28ebf144503b2b7597a34",
      name: "Group Channel",
      cover_url: "https://static.sendbird.com/sample/cover/cover_11.jpg",
      data: "",
      created_at: 1712158333,
      custom_type: "CHANNEL_USER",
      max_length_message: 5000,
      member_count: 2,
    },
    count_preference: "all",
    created_by: userMockupDodyy,
    disappearing_message: {
      is_triggered_by_message_read: false,
      message_survival_seconds: -1,
    },
    is_access_code_required: true,
    is_muted: false,
    is_push_enabled: true,
    member_state: "joined",
    message_survival_seconds: -1,
    my_role: "",
    push_trigger_option: "default",
    read_receipt: {
      [userMockupDodyy.user_id]: 1713337561127,
      [userMockupC.user_id]: 1712893833869,
    },
    sms_fallback: {
      wait_seconds: -1,
      exclude_user_ids: [],
    },
    ts_message_offset: 0,
    user_last_read: 1713337561127,
    inviter: {
      ...userMockupC,
      metadata: {},
    },
    invited_at: 1713337561127,
    is_hidden: false,
    hidden_state: "unhidden",
    last_message: {
      type: "MESG",
      message_id: 1712893833869,
      message: "Hi Momon!\nHow about this project?",
      data: "",
      custom_type: "",
      file: {},
      created_at: 1713341435492,
      user: userMockupC,
      channel_url:
        "sendbird_group_channel_418411068_2326cc40d54ee27f89a28ebf144503b2b7597a34",
      updated_at: 0,
      message_survival_seconds: -1,
      mentioned_users: [],
      mention_type: "users",
      silent: false,
      message_retention_hour: -1,
      channel_type: "group",
      translations: {},
      is_removed: false,
      req_id: "rq-ba033f4f-3faf-414b-b50b-5e811f69bb58",
      is_op_msg: false,
      message_events: {
        send_push_notification: "receivers",
        update_unread_count: true,
        update_mention_count: true,
        update_last_message: true,
      },
    },
    members: [
      {
        ...userMockupDodyy,
        metadata: {},
        is_online: true,
        last_seen_at: 0,
        state: "joined",
        is_active: true,
        is_blocked_by_me: false,
        friend_name: null,
        friend_discovery_key: null,
        role: "",
        is_muted: false,
        muted_end_at: -1,
        muted_description: "",
        is_blocking_me: false,
      },
      {
        ...userMockupC,
        metadata: {},
        is_online: false,
        last_seen_at: -1,
        state: "joined",
        is_active: true,
        is_blocked_by_me: false,
        friend_name: null,
        friend_discovery_key: null,
        role: "",
        is_muted: false,
        muted_end_at: -1,
        muted_description: "",
        is_blocking_me: false,
      },
    ],
    operators: [],
    joined_ts: 1713337561,
  },
  {
    channel_url:
      "sendbird_group_channel_4ssf411068_2326cc40d54ee27f89a28ebf144503b2b7597a34",
    name: "Group Channel",
    cover_url: "https://static.sendbird.com/sample/cover/cover_11.jpg",
    data: "",
    member_count: 0,
    joined_member_count: 0,
    max_length_message: 5000,
    created_at: 1712158333,
    custom_type: "CHANNEL_USER",
    is_distinct: false,
    is_super: false,
    is_broadcast: false,
    is_public: true,
    is_discoverable: true,
    freeze: false,
    is_ephemeral: false,
    unread_message_count: 2,
    unread_mention_count: 0,
    ignore_profanity_filter: false,
    id: 1106969225,
    channel: {
      channel_url:
        "sendbird_group_channel_4ssf411068_2326cc40d54ee27f89a28ebf144503b2b7597a34",
      name: "Group Channel",
      cover_url: "https://static.sendbird.com/sample/cover/cover_11.jpg",
      data: "",
      created_at: 1712158333,
      custom_type: "CHANNEL_USER",
      max_length_message: 5000,
      member_count: 2,
    },
    count_preference: "all",
    created_by: userMockupDodyy,
    disappearing_message: {
      is_triggered_by_message_read: false,
      message_survival_seconds: -1,
    },
    is_access_code_required: true,
    is_muted: false,
    is_push_enabled: true,
    member_state: "joined",
    message_survival_seconds: -1,
    my_role: "",
    push_trigger_option: "default",
    read_receipt: {
      [userMockupDodyy.user_id]: 1713337561127,
      [userMockupE.user_id]: 1712893833869,
    },
    sms_fallback: {
      wait_seconds: -1,
      exclude_user_ids: [],
    },
    ts_message_offset: 0,
    user_last_read: 1713337561127,
    inviter: {
      ...userMockupE,
      metadata: {},
    },
    invited_at: 1713337561127,
    is_hidden: false,
    hidden_state: "unhidden",
    last_message: {
      type: "MESG",
      message_id: 2178333742,
      message: "Hi Mì ❄️!\nHow about this project?",
      data: "",
      custom_type: "",
      file: {},
      created_at: 1713237635492,
      user: userMockupE,
      channel_url:
        "sendbird_group_channel_4ssf411068_2326cc40d54ee27f89a28ebf144503b2b7597a34",
      updated_at: 0,
      message_survival_seconds: -1,
      mentioned_users: [],
      mention_type: "users",
      silent: false,
      message_retention_hour: -1,
      channel_type: "group",
      translations: {},
      is_removed: false,
      req_id: "rq-ba033f4f-3faf-414b-b50b-5e811f69bb58",
      is_op_msg: false,
      message_events: {
        send_push_notification: "receivers",
        update_unread_count: true,
        update_mention_count: true,
        update_last_message: true,
      },
    },
    members: [
      {
        ...userMockupDodyy,
        metadata: {},
        is_online: true,
        last_seen_at: 0,
        state: "joined",
        is_active: true,
        is_blocked_by_me: false,
        friend_name: null,
        friend_discovery_key: null,
        role: "",
        is_muted: false,
        muted_end_at: -1,
        muted_description: "",
        is_blocking_me: false,
      },
      {
        ...userMockupE,
        metadata: {},
        is_online: false,
        last_seen_at: -1,
        state: "joined",
        is_active: true,
        is_blocked_by_me: false,
        friend_name: null,
        friend_discovery_key: null,
        role: "",
        is_muted: false,
        muted_end_at: -1,
        muted_description: "",
        is_blocking_me: false,
      },
    ],
    operators: [],
    joined_ts: 1713337561,
  },
  {
    channel_url:
      "sendbird_group_channel_4ssf411068_2326cc40d54ee27f89a28ebf144503b2w2317a34",
    name: "Team Review Anime 🍓",
    cover_url:
      "https://i.pinimg.com/736x/b8/6f/05/b86f052d99b84f5d77fa96771f6c75e1.jpg",
    data: "",
    member_count: 0,
    joined_member_count: 0,
    max_length_message: 5000,
    created_at: 1712158333,
    custom_type: "CHANNEL_GROUP",
    is_distinct: false,
    is_super: false,
    is_broadcast: false,
    is_public: true,
    is_discoverable: true,
    freeze: false,
    is_ephemeral: false,
    unread_message_count: 2,
    unread_mention_count: 0,
    ignore_profanity_filter: false,
    id: 1106969225,
    channel: {
      channel_url:
        "sendbird_group_channel_4ssf411068_2326cc40d54ee27f89a28ebf144503b2w2317a34",
      name: "Group Channel",
      cover_url:
        "https://i.pinimg.com/736x/b8/6f/05/b86f052d99b84f5d77fa96771f6c75e1.jpg",
      data: "",
      created_at: 1712158333,
      custom_type: "CHANNEL_GROUP",
      max_length_message: 5000,
      member_count: 2,
    },
    count_preference: "all",
    created_by: userMockupDodyy,
    disappearing_message: {
      is_triggered_by_message_read: false,
      message_survival_seconds: -1,
    },
    is_access_code_required: true,
    is_muted: false,
    is_push_enabled: true,
    member_state: "joined",
    message_survival_seconds: -1,
    my_role: "",
    push_trigger_option: "default",
    read_receipt: {
      [userMockupDodyy.user_id]: 1713337561127,
      [userMockupE.user_id]: 1712893833869,
    },
    sms_fallback: {
      wait_seconds: -1,
      exclude_user_ids: [],
    },
    ts_message_offset: 0,
    user_last_read: 1713337561127,
    inviter: {
      ...userMockupE,
      metadata: {},
    },
    invited_at: 1713337561127,
    is_hidden: false,
    hidden_state: "unhidden",
    last_message: {
      type: "MESG",
      message_id: 2178333742,
      message: "Hi Mì ❄️!\nHow about this project?",
      data: "",
      custom_type: "",
      file: {},
      created_at: 1712893833869,
      user: userMockupE,
      channel_url:
        "sendbird_group_channel_4ssf411068_2326cc40d54ee27f89a28ebf144503b2w2317a34",
      updated_at: 0,
      message_survival_seconds: -1,
      mentioned_users: [],
      mention_type: "users",
      silent: false,
      message_retention_hour: -1,
      channel_type: "group",
      translations: {},
      is_removed: false,
      req_id: "rq-ba033f4f-3faf-414b-b50b-5e811f69bb58",
      is_op_msg: false,
      message_events: {
        send_push_notification: "receivers",
        update_unread_count: true,
        update_mention_count: true,
        update_last_message: true,
      },
    },
    members: [
      {
        ...userMockupDodyy,
        metadata: {},
        is_online: true,
        last_seen_at: 0,
        state: "joined",
        is_active: true,
        is_blocked_by_me: false,
        friend_name: null,
        friend_discovery_key: null,
        role: "",
        is_muted: false,
        muted_end_at: -1,
        muted_description: "",
        is_blocking_me: false,
      },
      {
        ...userMockupE,
        metadata: {},
        is_online: false,
        last_seen_at: -1,
        state: "joined",
        is_active: true,
        is_blocked_by_me: false,
        friend_name: null,
        friend_discovery_key: null,
        role: "",
        is_muted: false,
        muted_end_at: -1,
        muted_description: "",
        is_blocking_me: false,
      },
      {
        ...userMockupF,
        metadata: {},
        is_online: false,
        last_seen_at: -1,
        state: "joined",
        is_active: true,
        is_blocked_by_me: false,
        friend_name: null,
        friend_discovery_key: null,
        role: "",
        is_muted: false,
        muted_end_at: -1,
        muted_description: "",
        is_blocking_me: false,
      },
    ],
    operators: [],
    joined_ts: 1713337561,
  },
];
